version: '3'
services:
  communication:
    build: .
    container_name: COMMUNICATION
    command: npm run up
    volumes:
      - ./src:/usr/app/src
    environment:
      - REDIS_IS_CLUSTER=TRUE
      - REDIS_PASSWORD=
      - REDIS_LOGIN=
      - REDIS_PREFIX=TEST
      - REDIS_HOST=100.0.16.1 100.0.16.2 100.0.16.3 100.0.16.4 100.0.16.5 100.0.16.6
      - REDIS_PORT=6379
      - MYSQL_PORT=3306
      - MYSQL_HOST=192.168.0.10
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=q1
      - MYSQL_DATABASE=crm_gate_test
    ports:
      - "6068:6080"
      - "9856:9856"  # Hot front reload
    networks :
      - dockerrediscluster_redis_net
      - dockermysqlcluster_mysql_net

networks:
  dockermysqlcluster_mysql_net:
    external: true
  dockerrediscluster_redis_net:
    external: true
